### ISSUE TITLE
weird behaviour of phps explode within weikinn test image 

### ISSUE THREAD

**Issue by skoslitz** [ifl-geovis/weikinn-tools#1]
PHPs explode() with lineending delimiter creates weird behaviour under linux
see http://www.tehplayground.com/#GT6WLJ6Lx

**Comment by sspecht** [comment]
The behaviour is non-weird, if you use single quotation marks while  
defining variable $f:

LIKE THIS

$f ='D:\Weikinn_Scans\1802\nb_175_1802_Somm_Rheinpfalz.tif
D:\Weikinn_Scans\1802\ob_176_1802_Somm_Rheinpfa_a.tif';

NOT THIS

$f ="D:\Weikinn_Scans\1802\nb_175_1802_Somm_Rheinpfalz.tif
D:\Weikinn_Scans\1802\ob_176_1802_Somm_Rheinpfa_a.tif";

Double-quotation marks are always "parsed" / pre-processed / evaluated in  
PHP (e.g. for variables like "The error code is: $error_code") and this  
applies to \0 or \t or \n etc.

Am 12.09.2016, 13:59 Uhr, schrieb skoslitz notifications@github.com:

> PHPs explode() with lineending delimiter creates weird behaviour under  
> linux
> see http://www.tehplayground.com/#GT6WLJ6Lx
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

Sebastian Specht
Böversweg 2a
26131 Oldenburg

+49-441-8007425
